const CHANGE_VOLUME = 'SET_VOLUME';
const PLAY = 'SET_PLAY';
const MUTE = 'SET_MUTE';
const CHANGE_POSITION = 'SET_POSITION';
const INIT_VIDEO = 'SET_VIDEO';
const SET_DURATION = 'SET_DURATION';
const CHANGE_FULLSCREEN = 'CHANGE_FULLSCREEN';

export const ACTIONS = {
    CHANGE_VOLUME,
    PLAY,
    MUTE,
    CHANGE_POSITION,
    INIT_VIDEO,
    SET_DURATION,
    CHANGE_FULLSCREEN,
};
