const SET_VOLUME = 'SET_VOLUME';
const SET_PLAY = 'SET_PLAY';
const SET_MUTE = 'SET_MUTE';
const SET_POSITION = 'SET_POSITION';
const SET_VIDEO = 'SET_VIDEO';
const SET_DURATION = 'SET_DURATION';
const SET_FULLSCREEN = 'SET_FULLSCREEN';

export const MUTATIONS = {
    SET_VOLUME,
    SET_PLAY,
    SET_MUTE,
    SET_POSITION,
    SET_VIDEO,
    SET_DURATION,
    SET_FULLSCREEN,
};
